name: Docker CI

on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v4
      - name: Docker Login and setup
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and Push Multi-Platform Image - qbittorrent-openvpn-container
        uses: docker/build-push-action@v5
        with:
          context: qbittorrent-openvpn-container
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mattev02/qbittorrent-over-openvpn:latest
